### ISSUE TITLE
Surrounded by walls on OS X

### ISSUE THREAD

**Issue by newobj** [martin-tornqvist/ia#183] opened 2017-08-18 20:25 UTC
JFYI:

I got this to build on OSX mostly by the exact instructions given, with clang-802.0.42.

HOWEVER, I had to make one tweak: in the cmake config, i had to set CMAKE_CXX_FLAGS to "-std=c++14"

Thanks! Looking forward to playing this :)

**Comment by mjcampagna** [comment] 2017-08-24 06:35
@newobj, I've just built this for Mac and seems to have worked well, except that whenever I begin a new game, I'm stuck in a wall. I can seemingly access all of the game's functions, menus, etc., but my character is surrounded on all sides by walls. Less Lovecraft, more Poe it would seem ... I don't know whether the error is caused by my build process, or what's going on ... did you encounter any such thing? Have ye any advice?

**Comment by martin-tornqvist** [comment] 2017-08-24 06:40
@mjcampagna I've never heard of this before. Could you take a screenshot and drop it here?

**Comment by mjcampagna** [comment] 2017-08-24 07:59
<img width="1280" alt="ia_fortunato" src="https://user-images.githubusercontent.com/1414181/29655922-9178738c-88ed-11e7-97a4-353b859f06f8.png">

**Comment by mjcampagna** [comment] 2017-08-24 08:00
@martin-tornqvist This is using the same build and steps I sent you via email, in case having those files helps, and assuming you received that email.

**Comment by martin-tornqvist** [comment] 2017-08-24 08:17
This is bizarre.

Yes I received your email.

Hm... did you update the submodule? (I saw that this was an issue before).

**Comment by mjcampagna** [comment] 2017-08-24 09:40
Yes, I updated the submodule.

**Comment by martin-tornqvist** [comment] 2017-08-24 14:29
@mjcampagna Could you try deleting the build directory, and rebuild it completely from scratch?

**Comment by mjcampagna** [comment] 2017-08-24 15:34
Same result, building from tag v19.1. I'll try again from master, just to see whether it gives the same result. In the meantime, here's my terminal log, in case it helps.

$ git clone https://github.com/martin-tornqvist/ia.git
Cloning into 'ia'...
remote: Counting objects: 26761, done.
remote: Total 26761 (delta 0), reused 0 (delta 0), pack-reused 26761
Receiving objects: 100% (26761/26761), 99.69 MiB | 6.32 MiB/s, done.
Resolving deltas: 100% (22399/22399), done.

$ cd ia
$ git branch -a
* develop
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
  remotes/origin/master
  remotes/origin/multi-turn-armor-handling

$ git tag -l
v14.0
v14.1
v15.0
v16.0
v16.0_RC1
v17.0
v18.0
v18.1
v18.2
v19.0
v19.1
v19.1-beta.1
v19.1-beta.2

$ git checkout tags/v19.1
Note: checking out 'tags/v19.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 26c18c0c... Added release date to changelog

$ git branch -a
* (HEAD detached at v19.1)
  develop
  master
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
  remotes/origin/master
  remotes/origin/multi-turn-armor-handling

$ git submodule init
Submodule 'rl_utils' (https://martin-tornqvist@github.com/martin-tornqvist/rl_utils.git) registered for path 'rl_utils'

$ git submodule update
Cloning into '/Users/mjcampagna/Gaming/Roguelike/_roguelike_pile/Infra Arcanum/ia/rl_utils'...
Submodule path 'rl_utils': checked out '86c9cc3dfca4782f78050c282e435168d2b7ba29'

$ mkdir build
$ cd build
$ cmake ../
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
<FindSDL2.cmake>
</FindSDL2.cmake>
-- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.dylib;-framework Cocoa  
-- Found SDL2_image: /usr/local/lib/libSDL2_image.dylib (found version "..") 
-- Found SDL2_mixer: /usr/local/lib/libSDL2_mixer.dylib (found version "2.0.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mjcampagna/Gaming/Roguelike/_roguelike_pile/Infra Arcanum/ia/build

$ make ia
Scanning dependencies of target ia
[  0%] Building CXX object CMakeFiles/ia.dir/src/ability_values.cpp.o
[  0%] Building CXX object CMakeFiles/ia.dir/src/actor.cpp.o
[  2%] Building CXX object CMakeFiles/ia.dir/src/actor_data.cpp.o
[  2%] Building CXX object CMakeFiles/ia.dir/src/actor_factory.cpp.o
[  4%] Building CXX object CMakeFiles/ia.dir/src/actor_mon.cpp.o
[  4%] Building CXX object CMakeFiles/ia.dir/src/actor_player.cpp.o
[  6%] Building CXX object CMakeFiles/ia.dir/src/ai.cpp.o
[  6%] Building CXX object CMakeFiles/ia.dir/src/art.cpp.o
[  8%] Building CXX object CMakeFiles/ia.dir/src/attack.cpp.o
[  8%] Building CXX object CMakeFiles/ia.dir/src/audio.cpp.o
[ 10%] Building CXX object CMakeFiles/ia.dir/src/bot.cpp.o
[ 10%] Building CXX object CMakeFiles/ia.dir/src/browser.cpp.o
[ 12%] Building CXX object CMakeFiles/ia.dir/src/character_descr.cpp.o
[ 12%] Building CXX object CMakeFiles/ia.dir/src/close.cpp.o
[ 14%] Building CXX object CMakeFiles/ia.dir/src/colors.cpp.o
[ 14%] Building CXX object CMakeFiles/ia.dir/src/config.cpp.o
[ 16%] Building CXX object CMakeFiles/ia.dir/src/create_character.cpp.o
[ 16%] Building CXX object CMakeFiles/ia.dir/src/disarm.cpp.o
[ 18%] Building CXX object CMakeFiles/ia.dir/src/drop.cpp.o
[ 18%] Building CXX object CMakeFiles/ia.dir/src/explosion.cpp.o
[ 20%] Building CXX object CMakeFiles/ia.dir/src/feature.cpp.o
[ 20%] Building CXX object CMakeFiles/ia.dir/src/feature_data.cpp.o
[ 22%] Building CXX object CMakeFiles/ia.dir/src/feature_door.cpp.o
[ 22%] Building CXX object CMakeFiles/ia.dir/src/feature_event.cpp.o
[ 24%] Building CXX object CMakeFiles/ia.dir/src/feature_mob.cpp.o
[ 24%] Building CXX object CMakeFiles/ia.dir/src/feature_monolith.cpp.o
[ 24%] Building CXX object CMakeFiles/ia.dir/src/feature_pylon.cpp.o
[ 26%] Building CXX object CMakeFiles/ia.dir/src/feature_rigid.cpp.o
[ 26%] Building CXX object CMakeFiles/ia.dir/src/feature_trap.cpp.o
[ 28%] Building CXX object CMakeFiles/ia.dir/src/fov.cpp.o
[ 28%] Building CXX object CMakeFiles/ia.dir/src/game.cpp.o
[ 30%] Building CXX object CMakeFiles/ia.dir/src/game_time.cpp.o
[ 30%] Building CXX object CMakeFiles/ia.dir/src/gods.cpp.o
[ 32%] Building CXX object CMakeFiles/ia.dir/src/highscore.cpp.o
[ 32%] Building CXX object CMakeFiles/ia.dir/src/init.cpp.o
[ 34%] Building CXX object CMakeFiles/ia.dir/src/insanity.cpp.o
[ 34%] Building CXX object CMakeFiles/ia.dir/src/inventory.cpp.o
[ 36%] Building CXX object CMakeFiles/ia.dir/src/inventory_handling.cpp.o
[ 36%] Building CXX object CMakeFiles/ia.dir/src/io.cpp.o
[ 38%] Building CXX object CMakeFiles/ia.dir/src/item_artifact.cpp.o
[ 38%] Building CXX object CMakeFiles/ia.dir/src/item.cpp.o
[ 40%] Building CXX object CMakeFiles/ia.dir/src/item_data.cpp.o
[ 40%] Building CXX object CMakeFiles/ia.dir/src/item_device.cpp.o
[ 42%] Building CXX object CMakeFiles/ia.dir/src/item_factory.cpp.o
[ 42%] Building CXX object CMakeFiles/ia.dir/src/item_potion.cpp.o
[ 44%] Building CXX object CMakeFiles/ia.dir/src/item_rod.cpp.o
[ 44%] Building CXX object CMakeFiles/ia.dir/src/item_scroll.cpp.o
[ 46%] Building CXX object CMakeFiles/ia.dir/src/knockback.cpp.o
[ 46%] Building CXX object CMakeFiles/ia.dir/src/line_calc.cpp.o
[ 48%] Building CXX object CMakeFiles/ia.dir/src/look.cpp.o
[ 48%] Building CXX object CMakeFiles/ia.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/ia.dir/src/main_menu.cpp.o
[ 50%] Building CXX object CMakeFiles/ia.dir/src/manual.cpp.o
[ 50%] Building CXX object CMakeFiles/ia.dir/src/map.cpp.o
[ 52%] Building CXX object CMakeFiles/ia.dir/src/mapgen_aux_rooms.cpp.o
[ 52%] Building CXX object CMakeFiles/ia.dir/src/mapgen.cpp.o
[ 54%] Building CXX object CMakeFiles/ia.dir/src/mapgen_decorate.cpp.o
[ 54%] Building CXX object CMakeFiles/ia.dir/src/mapgen_doors.cpp.o
[ 56%] Building CXX object CMakeFiles/ia.dir/src/mapgen_merge_regions.cpp.o
[ 56%] Building CXX object CMakeFiles/ia.dir/src/mapgen_monolith.cpp.o
[ 58%] Building CXX object CMakeFiles/ia.dir/src/mapgen_pylon.cpp.o
[ 58%] Building CXX object CMakeFiles/ia.dir/src/mapgen_region.cpp.o
[ 60%] Building CXX object CMakeFiles/ia.dir/src/mapgen_river.cpp.o
[ 60%] Building CXX object CMakeFiles/ia.dir/src/mapgen_room.cpp.o
[ 62%] Building CXX object CMakeFiles/ia.dir/src/mapgen_special.cpp.o
[ 62%] Building CXX object CMakeFiles/ia.dir/src/mapgen_sub_rooms.cpp.o
[ 64%] Building CXX object CMakeFiles/ia.dir/src/mapgen_utils.cpp.o
[ 64%] Building CXX object CMakeFiles/ia.dir/src/map_parsing.cpp.o
[ 66%] Building CXX object CMakeFiles/ia.dir/src/map_patterns.cpp.o
[ 66%] Building CXX object CMakeFiles/ia.dir/src/map_templates.cpp.o
[ 68%] Building CXX object CMakeFiles/ia.dir/src/map_travel.cpp.o
[ 68%] Building CXX object CMakeFiles/ia.dir/src/marker.cpp.o
[ 70%] Building CXX object CMakeFiles/ia.dir/src/msg_log.cpp.o
[ 70%] Building CXX object CMakeFiles/ia.dir/src/pickup.cpp.o
[ 72%] Building CXX object CMakeFiles/ia.dir/src/player_bon.cpp.o
[ 72%] Building CXX object CMakeFiles/ia.dir/src/player_spells.cpp.o
[ 74%] Building CXX object CMakeFiles/ia.dir/src/populate_items.cpp.o
[ 74%] Building CXX object CMakeFiles/ia.dir/src/populate_monsters.cpp.o
[ 74%] Building CXX object CMakeFiles/ia.dir/src/populate_traps.cpp.o
[ 76%] Building CXX object CMakeFiles/ia.dir/src/popup.cpp.o
[ 76%] Building CXX object CMakeFiles/ia.dir/src/postmortem.cpp.o
[ 78%] Building CXX object CMakeFiles/ia.dir/src/properties.cpp.o
[ 78%] Building CXX object CMakeFiles/ia.dir/src/query.cpp.o
[ 80%] Building CXX object CMakeFiles/ia.dir/src/reload.cpp.o
[ 80%] Building CXX object CMakeFiles/ia.dir/src/room.cpp.o
[ 82%] Building CXX object CMakeFiles/ia.dir/src/saving.cpp.o
[ 82%] Building CXX object CMakeFiles/ia.dir/src/sdl_base.cpp.o
[ 84%] Building CXX object CMakeFiles/ia.dir/src/sound.cpp.o
[ 84%] Building CXX object CMakeFiles/ia.dir/src/spells.cpp.o
[ 86%] Building CXX object CMakeFiles/ia.dir/src/state.cpp.o
[ 86%] Building CXX object CMakeFiles/ia.dir/src/status_lines.cpp.o
[ 88%] Building CXX object CMakeFiles/ia.dir/src/text_format.cpp.o
[ 88%] Building CXX object CMakeFiles/ia.dir/src/throwing.cpp.o
[ 90%] Building CXX object CMakeFiles/ia.dir/src/wham.cpp.o
[ 90%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/bresenham.cpp.o
[ 92%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/direction.cpp.o
[ 92%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/flood.cpp.o
[ 94%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/misc.cpp.o
[ 94%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/pathfind.cpp.o
[ 96%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/pos.cpp.o
[ 96%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/random.cpp.o
[ 98%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/rl_utils.cpp.o
[ 98%] Building CXX object CMakeFiles/ia.dir/rl_utils/src/time.cpp.o
[100%] Linking CXX executable ia
[100%] Built target ia

**Comment by mjcampagna** [comment] 2017-08-28 05:25
Hi, just checking in on this. Any ideas why 19.1 is building with such a problem, while 19.0 builds correctly?

**Comment by martin-tornqvist** [comment] 2017-08-31 06:18
@mjcampagna I haven't really had a chance to troubleshoot this - and to be honest I'm not sure how I'd even do that, since I can't recreate the issue (no acces to a Mac).

I suppose I could make a branch, and add tons of debug prints. Then you build from this branch and upload the output somewhere.

I can also tell you that I've now seen one other player with this issue, so it's not just a problem on your side.

**Comment by mjcampagna** [comment] 2017-08-31 07:54
@martin-tornqvist Glad to hear it's being looked into. If there's something I can do to help with debugging, please let me know, either here or via email. This is one of my favorite roguelikes, so I not only want to ensure I can build 19.1, but that the issue will be solved going forward to 20.0, 21.0, etc.

**Comment by martin-tornqvist** [comment] 2017-09-10 09:06
OK, I have implemented something which might help us understand this issue: c0cb99dfbf263f1e07c3009f6bcf7775013f4461

If you build a debug version of the game (**make ia-debug**), a "map generation demo" can be enabled with a command line option: "--demo-mapgen".

So it would be great if someone who has this "surrounded by walls" issue could try this out, and report back here what you see (or perhaps even record a demo).

For example, it would be interesting to see if a normal map is actually generated, and then filled with walls - or if it just puts walls and leaves it at that, without ever creating any rooms etc.

So the steps are:
```
mkdir build
cd build
cmake ..
make ia-debug
./ia-debug --demo-mapgen
```

**Comment by mjcampagna** [comment] 2017-09-11 05:29
Here's a fun twist. I built ia-debug from the develop branch, ran as above with the --demo-mapgen flag, and the game loads correctly.  I'm outside the church, normal beginning. 

Is there anything you'd like me to run as a test?

**Comment by martin-tornqvist** [comment] 2017-09-11 05:47
When you had this issue:
* Did it happen 100% of the time, or only occasionally?
* Was the intro (forest and church) level (i.e. dlvl 0) loading correctly?
Or were you surrounded by walls already on dlvl 0? This level is loaded
from an external template file, so it could have something to do with not
loading this file correctly.
* Did you have "skip intro level" enabled in the options?
* After running "make ia", did you start the game while standing in the
"build" directory, or did you do something else (such as copy it
somewhere)? I've seen people mention that just running "make ia" will not
create a standalone installation that you can copy around, this is what
"make install" is for.


On Sep 11, 2017 07:29, "Matthew Campagna" <notifications@github.com> wrote:

Here's a fun twist. I built ia-debug from the develop branch, ran as above
with the --demo-mapgen flag, and the game loads correctly. I'm outside the
church, normal beginning.

Is there anything you'd like me to run as a test?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/martin-tornqvist/ia/issues/183#issuecomment-328419456>,
or mute the thread

**Comment by mjcampagna** [comment] 2017-09-11 06:18
> Did it happen 100% of the time, or only occasionally?

100%

> Was the intro (forest and church) level (i.e. dlvl 0) loading correctly? Or were you surrounded by walls already on dlvl 0?

Presumably, the intro. I haven't changed any settings from default, and that's where the game is starting up on this load.

> Did you have "skip intro level" enabled in the options?

Disabled.

> After running "make ia", did you start the game while standing in the "build" directory, or did you do something else (such as copy it somewhere)?

Both.

----

So, I still have my previous 19.1 build. Based on your questions, I loaded it up. Disabled the intro level and started a new game, and it looks like the dungeon (dlvl 1) is loading correctly. Issue seems to be the intro level then.

This is also a copy that has been moved out of the build location. I've copied the ia file, and the res folder.

As I recall, though, moving or not moving the build had no impact on the wall issue. It occurred in both places. I ultimately moved the application just to hold onto it in case it needed to be revisited in the course of this conversation.

**Comment by martin-tornqvist** [comment] 2017-09-19 20:43
@mjcampagna So, whatever the issue was, it seems like it's fixed now?

**Comment by mjcampagna** [comment] 2017-09-20 05:20
Sorry, I've been busy lately and haven't tried playing. I just ran a new build of the 'develop' branch, in the regular fashion, not building debug. The map appears to be working now; I was not walled in.

Another possible oddity, there were no enemies in the intro map. Aren't there supposed to be wolves or something out there? I then wandered around the first dungeon for a while and was beginning to get worried, as I had plenty to find, but nothing to fight. Eventually, though, some rats did appear in one of the chambers. So hopefully that sounds consistent with your intentions for map generation and enemy population. Otherwise, I'm not seeing any obvious problems at this point.

**Comment by martin-tornqvist** [comment] 2017-09-21 21:13
>there were no enemies in the intro map

That's on purpose. Since there is no longer any benefit for playing this map (no XP for killing monsters), it doesn't make sense to have monsters there. I like it the way it is now, it's just a tour of the gravestones and a mood setter, which you can skip if you want without losing any advantage.

Closing the issue.

**Closed by martin-tornqvist** 2017-09-21 21:13 UTC
Labels: Critical bug
