### ISSUE TITLE
Segfault: exp by id-ing insight

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#133] opened 2016-11-06 10:29 UTC
Hi I quaff-id-ed a potion of insight. It then id-ed another potion for me. So I got 2x10exp. The game quit with a segfault. I believe I would have leveled up with that Exp, but I dont know for sure.

**Comment by martin-tornqvist** [comment] 2016-11-06 14:09
Which commit was this build based on? Because I think this was already fixed by 9b12edf21081eac907a8f4840ebb915076b97e34.

**Comment by hubertig** [comment] 2016-11-06 14:26
I don't know git well enough to say. Pulled about 5 days ago or so.

**Comment by martin-tornqvist** [comment] 2016-11-06 14:33
Ok, then it definitely has been fixed already. The commit is from 3 days ago, and I'm fairly sure that the cause of your crash is the same issue that this commit fixed.

**Closed by martin-tornqvist** 2016-11-06 14:33 UTC
Labels: Investigation
