### ISSUE TITLE
Crash on Death to Gas Spore Explosion

### ISSUE THREAD

**Issue by zxc23** [martin-tornqvist/ia#126] opened 2016-07-27 16:17 UTC
http://i.imgur.com/Acsfcgq.png

Version 18.1
Windows 10 x64

There were two gas spores. I was full hp at the time that I threw the knife. I was wounded at the time of death as well.

No idea if this is repeatable.

**Comment by martin-tornqvist** [comment] 2016-07-27 20:09
Thanks for informing me. I've seen a couple of other players mention crash problems related to the spores as well, but only in v18.0 (or maybe 18.1). So it's very relevant information that something strange is still going on in 18.2.

It seems pretty rare though. I've only ever heard it like once or twice before, and I'm not sure if I ever saw it myself. So I currently have no idea how to recreate the bug. Just going around throwing knives at spores has never crashed the game for me while investigating this bug.

Need to get to the bottom of what is causing this...

**Comment by zxc23** [comment] 2016-07-28 03:51
Fixed the link.

I've just realised that ingame it says v18.1, so I guess I got that part wrong! Oops. I had extracted v18.2 over the top of it and assumed it was updated,

I deleted everything but the data folder and extracted it (also re-downloaded for good measure) and couldn't get it to run: http://i.imgur.com/g8lgzoL.png

Then I tried deleting the config file in the data folder and it worked, but it opens an additional window: http://i.imgur.com/QKUjAUh.png

But at least I have v18.2 working now :)

Noticed that there is no Infra Arcana.exe in this one.

**Comment by martin-tornqvist** [comment] 2016-07-28 08:13
Yeah you should extract a new version in a completely new folder. The
config file, highscores, and save file are most likely not compatible
across versions. No idea why it opened two windows for you, never seen that
before. But it's best if you just delete the old version completely before
getting the new one.

The game is relatively short, and there's not a huge amount of options, so
I figured it's not worth it to keep the data files compatible across
versions.

**Comment by ShadesOfRain** [comment] 2016-08-14 01:13
Try standing close enough to the spores that you die. The reason you're not reproducing it might be because you are only testing the explosions themselves, rather than testing all the possible cases where you die while standing near an exploding spore..

It might also have something to do with being near multiple spores at the same time when they explode. Not sure.

Every time this bug has happened to me in the game I was standing near multiple spores, threw an object at one of them, and died in the blast, after which it crashed to desktop. The bug is not rare. It seems to happen every time I'm ever killed by a spore.

**Comment by martin-tornqvist** [comment] 2016-08-15 20:00
> Try standing close enough to the spores that you die.
I did, many times and with different circumstances (like one or multiple spores, dying or not dying, being wounded or not, wearing a gasmask or not, wearing armor or not, and so on).

> Oh, and I've been playing the 18.1 Oryx tile version of the game when it happens. Don't know about any of the other versions.
Yeah I've gotten multiple reports about this from 18.0 and 18.1. But never in 18.2, so I'm kind of assuming it's been fixed at the moment - but I'm keeping this issue, and my eyes, open for it.

**Comment by martin-tornqvist** [comment] 2017-11-04 12:23
This conversation is more than a year old now - and never heard of Gas Spore crashes since then. Closing the issue.

**Closed by martin-tornqvist** 2017-11-04 12:23 UTC
Labels: Critical bug
