### ISSUE TITLE
Player should not telepathically see allies

### ISSUE THREAD

**Issue by Lain-** [martin-tornqvist/ia#111] opened 2016-02-21 11:50 UTC
I noticed this with the Ghoul background, my character can see and hear his spawned Worm Mass (displayed as ! with green background) without direct line-of-sight. This probably shouldn't happen.

Probably applies to friendly creatures in general too, not just Worm Mass from the Ghoul background.

**Comment by martin-tornqvist** [comment] 2016-03-07 20:30
Yes it applies to all allied creatures, and it's by design. But I agree it doesn't really make sense; I don't even know why I did it like that.

I'll update so you aren't telepathically aware of them.

**Comment by martin-tornqvist** [comment] 2016-03-12 17:14
Fixed by: f3d8d0c47f959058ee701bb6732114915ad0a543

**Closed by martin-tornqvist** 2016-03-12 17:14 UTC
Labels: Enhancement
